name: Deploy Live

on:
  push:
    branches:
      - live

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Frontend (Live)
        run: |
          npx ng build --configuration production --base-href https://demohandler.in/
          echo "Deployed at: $(date)" > ./dist/demo-handler/browser/deploy-timestamp.txt

      - name: Deploy Frontend to Live
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_LIVE }}
          username: ${{ secrets.FTP_USERNAME_LIVE }}
          password: ${{ secrets.FTP_PASSWORD_LIVE }}
          port: 21
          protocol: ftp
          local-dir: ./dist/demo-handler/browser/
          server-dir: public_html/
          timeout: 60000
          dangerous-clean-slate: false
          exclude: |
            **/.htaccess
            **/.well-known/**
            cgi-bin/**
            api/**
            images/**
            php/**
            error_log
            .DS_Store
            .git/**
            .github/**
